AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  s3 bucket creation infra

Resources:
  EBSReapers3Bucket: 
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "Private"
      BucketName: "seceng-ebs-reaper-bucket"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: "Enabled"

  s3BucketPolicy:
    DependsOn: EBSReapers3Bucket
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: "seceng-ebs-reaper-bucket"
      PolicyDocument:
        Statement:
          - Sid: "AllowLambdaAccess"
            Effect: "Allow"
            Principal:
              AWS: "arn:aws:iam::11111111111:role/seceng-ebs-reaper-lambda-role"
            Action:
              - "s3:*"
            Resource: "arn:aws:s3:::seceng-ebs-reaper-bucket"
          - Sid: "ForceSSLOnlyAccess"
            Effect: "Deny"
            Principal:
              AWS: "*"
            Action:
              - "s3:*"
            Resource: "arn:aws:s3:::seceng-ebs-reaper-bucket"
            Condition:
              Bool:
                aws:SecureTransport: false
